/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();  
    group.current.rotation.y = a / 2;
  });
  const group = useRef()
  const { nodes, materials } = useGLTF('/wiz_master.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0, 3.18916869, 0]}
        scale={[0.48778152, 0.5099107, 0.45003331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0, 3.73370099, 0]}
        scale={[0.83441997, 0.03462154, 0.81656736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0, 4.11389685, 0]}
        scale={[0.34500784, 0.20760809, 0.31830853]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-0.18979251, 4.29316092, -0.15745892]}
        scale={[0.27977818, 0.10181191, 0.25812683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.40103018, 4.45272636, -0.33914226]}
        scale={[0.19716296, 0.05775347, 0.18190499]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.55383164, 4.55161858, -0.47843283]}
        scale={[0.11556427, 0.04113881, 0.10662104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-0.52029502, 3.30459428, -0.03439415]}
        scale={[0.08011124, 0.14883454, 0.04527115]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[0, 3.15047288, 0.50727862]}
        scale={[0.11419222, 0.08015293, 0.05724534]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[0, 3.2823534, 0.50727862]}
        scale={[0.07404009, 0.05172747, 0.05724534]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[0, 2.87953925, 0.46245646]}
        scale={[0.2940996, 0.18635584, 0.01242315]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-0.49639022, 3.07560682, 0.03452693]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.11419222, 0.08015293, 0.00860869]}
      />
      <group
        position={[-0.23900369, 3.41537857, 0.45911944]}
        scale={[0.11061922, 0.05818476, 0.0070218]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={nodes.Cube014_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={nodes.Cube014_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-0.3012895, 3.50321174, 0.45911944]}
        scale={[0.02097512, 0.02097512, 0.00830567]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[0, 2.61573792, 0]}
        scale={[0.20050478, 0.06352002, 0.18498822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[0, 2.48869801, -0.01495734]}
        scale={[0.45467651, 0.06352002, 0.39229217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[0.55614924, 2.42299151, 0]}
        scale={[0.10147271, 0.01266775, 0.18498822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[0.81608391, 2.26527596, 0]}
        scale={[0.10147271, 0.01266775, 0.18498822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[1.04218829, 2.17185354, 0]}
        scale={[0.06764247, 0.00844442, 0.11600362]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[1.285833, 2.17185354, 0]}
        scale={[0.04367322, 0.00974415, 0.13385849]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-1.17451727, 2.17185354, 0]}
        scale={[0.06764247, 0.00844442, 0.11600362]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-1.18384135, 2.17185354, 0.23200727]}
        scale={[0.05831842, 0.00844442, 0.11600361]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-1.19884837, 2.17185354, 0.47238615]}
        scale={[0.06645352, 0.01014841, 0.12437529]}
      />
      <group
        position={[-1.11508489, 2.19333744, 0.35898703]}
        scale={[0.05831842, 0.03277222, 0.11600361]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_1.geometry}
          material={materials['wood stick']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_2.geometry}
          material={materials['magic top']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[0.23167676, 0.697101, -0.01495734]}
        scale={[0.13151871, 0.02448293, 0.12428988]}
      />
      <group position={[0.23167676, 0.04963553, -0.01495734]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={nodes.Cube031_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_2.geometry}
          material={nodes.Cube031_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[0.55614924, 2.42299151, 0]}
        scale={[0.10147271, 0.01266775, 0.18498822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[0.81608391, 2.26527596, 0]}
        scale={[0.10147271, 0.01266775, 0.18498822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[1.11017513, 2.30186749, 0]}
        scale={[0.01287629, 0.00161476, 0.05668299]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[1.34728479, 2.30186749, 0]}
        scale={[0.01287629, 0.00161476, 0.05668299]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[1.34728479, 2.39817643, 0]}
        scale={[0.00989322, 0.00520832, 0.02731264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[1.11075318, 2.39817643, 0]}
        scale={[0.00989322, 0.00520832, 0.02731264]}
      />
      <group
        position={[1.23127484, 2.60593629, -0.01091162]}
        scale={[0.06895036, 0.00974415, 0.27777767]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_1.geometry}
          material={materials.owl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038_2.geometry}
          material={nodes.Cube038_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.beak}
        position={[1.22620678, 2.87575269, 0.26174706]}
        scale={[0.00989322, 0.00302009, 0.01081077]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        position={[1.43994653, 2.56281567, 0]}
        scale={[0.00474772, 0.00901382, 0.18309635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        position={[0, 1.85418117, 2.6693821]}
        scale={[1.98539674, 0.08876294, 1.22816098]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={nodes.Cube035.material}
        position={[0, 1.67804766, 2.66003156]}
        scale={[1.8374573, 0.08737058, 1.05957699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials.chair}
        position={[0, 1.39078951, -1.69529474]}
        scale={[0.76280534, 0.05641966, 0.64461374]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['red cushion']}
        position={[0, 1.26217067, -1.47108078]}
        scale={[0.76280528, 0.72374982, 0.72374982]}
      />
      <group
        position={[-0.05777039, 2.04506111, 2.54863667]}
        scale={[1.21059716, 1.21059716, 1.21059716]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_2.geometry}
          material={materials['red book']}
        />
      </group>
      <group
        position={[1.52400601, 2.02016425, 2.75239015]}
        scale={[0.26575258, 0.05273569, 0.25957501]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['magic ball']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={nodes.Cube020_2.material}
        />
      </group>
      <group
        position={[-1.25528526, 2.03778791, 2.66958117]}
        scale={[0.07035939, 0.07035939, 0.07035939]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_1.geometry}
          material={nodes.Cube022_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_2.geometry}
          material={nodes.Cube022_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_3.geometry}
          material={nodes.Cube022_3.material}
        />
      </group>
      <group
        position={[-1.60608351, 2.03778791, 2.42494559]}
        scale={[0.07035939, 0.07035939, 0.07035939]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_1.geometry}
          material={nodes.Cube070_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_2.geometry}
          material={nodes.Cube070_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_3.geometry}
          material={nodes.Cube070_3.material}
        />
      </group>
      <group
        position={[-1.71686196, 2.03778791, 2.7878356]}
        scale={[0.07035939, 0.07035939, 0.07035939]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071.geometry}
          material={nodes.Cube071.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_1.geometry}
          material={nodes.Cube071_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_2.geometry}
          material={nodes.Cube071_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={nodes.Cube075.material}
        position={[0.7650485, 1.2845844, -0.75846183]}
        scale={[0.03285236, 0.03285236, 0.03285236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={nodes.Cube076.material}
        position={[0.81638163, 1.26969898, -0.75846183]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube113.geometry}
        material={nodes.Cube113.material}
        position={[0.83955276, 1.23273742, -0.75846183]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube114.geometry}
        material={nodes.Cube114.material}
        position={[0.85621142, 1.19577587, -0.75846183]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube115.geometry}
        material={nodes.Cube115.material}
        position={[0.87320936, 1.15881431, -0.75846183]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube116.geometry}
        material={nodes.Cube116.material}
        position={[0.79684925, 1.26969898, -0.72600234]}
        rotation={[0, -0.74993596, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube117.geometry}
        material={nodes.Cube117.material}
        position={[0.81380433, 1.23273742, -0.71020907]}
        rotation={[0, -0.74993596, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube118.geometry}
        material={nodes.Cube118.material}
        position={[0.82599401, 1.19577587, -0.69885468]}
        rotation={[0, -0.74993596, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube119.geometry}
        material={nodes.Cube119.material}
        position={[0.83843195, 1.15881431, -0.68726903]}
        rotation={[0, -0.74993596, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube120.geometry}
        material={nodes.Cube120.material}
        position={[0.7507658, 1.26969898, -0.71331942]}
        rotation={[0, -1.56372515, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube121.geometry}
        material={nodes.Cube121.material}
        position={[0.75092965, 1.23273742, -0.69014889]}
        rotation={[0, -1.56372515, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={nodes.Cube122.material}
        position={[0.75104743, 1.19577587, -0.67349064]}
        rotation={[0, -1.56372515, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube123.geometry}
        material={nodes.Cube123.material}
        position={[0.75116754, 1.15881431, -0.65649313]}
        rotation={[0, -1.56372515, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube124.geometry}
        material={nodes.Cube124.material}
        position={[0.75669229, 1.2845844, -2.12751317]}
        rotation={[-Math.PI, 1.56126724, -Math.PI]}
        scale={[0.03285236, 0.03285236, 0.03285236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube129.geometry}
        material={nodes.Cube129.material}
        position={[0.78884739, 1.26969898, -2.15962195]}
        rotation={[0, 0.83038771, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube130.geometry}
        material={nodes.Cube130.material}
        position={[0.80447841, 1.23273742, -2.17672658]}
        rotation={[0, 0.83038771, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131.geometry}
        material={nodes.Cube131.material}
        position={[0.81571615, 1.19577587, -2.18902397]}
        rotation={[0, 0.83038771, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube132.geometry}
        material={nodes.Cube132.material}
        position={[0.82718277, 1.15881431, -2.2015717]}
        rotation={[0, 0.83038771, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube133.geometry}
        material={nodes.Cube133.material}
        position={[0.80196875, 1.26969898, -2.11366129]}
        rotation={[0, 0.01659598, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube134.geometry}
        material={nodes.Cube134.material}
        position={[0.82513666, 1.23273742, -2.11404586]}
        rotation={[0, 0.01659598, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube135.geometry}
        material={nodes.Cube135.material}
        position={[0.841793, 1.19577587, -2.11432242]}
        rotation={[0, 0.01659598, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube136.geometry}
        material={nodes.Cube136.material}
        position={[0.85878861, 1.15881431, -2.11460447]}
        rotation={[0, 0.01659598, 0]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube137.geometry}
        material={nodes.Cube137.material}
        position={[-0.74988669, 1.2845844, -2.12128282]}
        rotation={[-Math.PI, -0.00559291, -Math.PI]}
        scale={[0.03285236, 0.03285236, 0.03285236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube138.geometry}
        material={nodes.Cube138.material}
        position={[-0.80121899, 1.26969898, -2.12099528]}
        rotation={[-Math.PI, -0.00559291, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube139.geometry}
        material={nodes.Cube139.material}
        position={[-0.82438993, 1.23273742, -2.12086582]}
        rotation={[-Math.PI, -0.00559291, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube140.geometry}
        material={nodes.Cube140.material}
        position={[-0.84104788, 1.19577587, -2.12077284]}
        rotation={[-Math.PI, -0.00559291, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube141.geometry}
        material={nodes.Cube141.material}
        position={[-0.85804576, 1.15881431, -2.12067771]}
        rotation={[-Math.PI, -0.00559291, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube142.geometry}
        material={nodes.Cube142.material}
        position={[-0.78186852, 1.26969898, -2.15356374]}
        rotation={[-Math.PI, 0.74434368, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube143.geometry}
        material={nodes.Cube143.material}
        position={[-0.79891163, 1.23273742, -2.16926217]}
        rotation={[-Math.PI, 0.74434368, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube144.geometry}
        material={nodes.Cube144.material}
        position={[-0.81116468, 1.19577587, -2.18054819]}
        rotation={[-Math.PI, 0.74434368, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube145.geometry}
        material={nodes.Cube145.material}
        position={[-0.82366717, 1.15881431, -2.19206381]}
        rotation={[-Math.PI, 0.74434368, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube150.geometry}
        material={nodes.Cube150.material}
        position={[-0.76503664, 1.2845844, -0.76252365]}
        rotation={[-Math.PI, -1.56864981, -Math.PI]}
        scale={[0.03285236, 0.03285236, 0.03285236]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube151.geometry}
        material={nodes.Cube151.material}
        position={[-0.76514745, 1.26969898, -0.71119064]}
        rotation={[-Math.PI, -1.56864981, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube152.geometry}
        material={nodes.Cube152.material}
        position={[-0.76519775, 1.23273742, -0.68801934]}
        rotation={[-Math.PI, -1.56864981, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube153.geometry}
        material={nodes.Cube153.material}
        position={[-0.76523405, 1.19577587, -0.67136109]}
        rotation={[-Math.PI, -1.56864981, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube154.geometry}
        material={nodes.Cube154.material}
        position={[-0.76527083, 1.15881431, -0.65436298]}
        rotation={[-Math.PI, -1.56864981, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube155.geometry}
        material={nodes.Cube155.material}
        position={[-0.79756474, 1.26969898, -0.73079312]}
        rotation={[-Math.PI, -0.81869352, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube156.geometry}
        material={nodes.Cube156.material}
        position={[-0.81339496, 1.23273742, -0.71387231]}
        rotation={[-Math.PI, -0.81869352, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157.geometry}
        material={nodes.Cube157.material}
        position={[-0.8247757, 1.19577587, -0.70170724]}
        rotation={[-Math.PI, -0.81869352, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube158.geometry}
        material={nodes.Cube158.material}
        position={[-0.83638799, 1.15881431, -0.68929458]}
        rotation={[-Math.PI, -0.81869352, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube159.geometry}
        material={nodes.Cube159.material}
        position={[-0.81014794, 1.26969898, -0.77690393]}
        rotation={[-Math.PI, -0.0049015, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube160.geometry}
        material={nodes.Cube160.material}
        position={[-0.83331859, 1.23273742, -0.77679044]}
        rotation={[-Math.PI, -0.0049015, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube161.geometry}
        material={nodes.Cube161.material}
        position={[-0.84997708, 1.19577587, -0.77670872]}
        rotation={[-Math.PI, -0.0049015, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube162.geometry}
        material={nodes.Cube162.material}
        position={[-0.86697489, 1.15881431, -0.77662534]}
        rotation={[-Math.PI, -0.0049015, -Math.PI]}
        scale={[0.01848076, 0.01848076, 0.01848076]}
      />
      <group
        position={[-0.51913834, 2.03764009, 3.48277926]}
        rotation={[0, 0.48427409, 0]}
        scale={[0.06596096, 0.05947227, 0.26349956]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_1.geometry}
          material={materials['scroll ']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_2.geometry}
          material={nodes.Cube069_2.material}
        />
      </group>
      <group position={[0.23167676, 0.04963553, -0.01495734]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064.geometry}
          material={nodes.Cube064.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_1.geometry}
          material={nodes.Cube064_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube268.geometry}
        material={nodes.Cube268.material}
        position={[0.23167676, 0.697101, -0.01495734]}
        scale={[0.13151871, 0.02448293, 0.12428988]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube269.geometry}
        material={nodes.Cube269.material}
        position={[-0.3012895, 3.50321174, 0.45911944]}
        scale={[0.02097512, 0.02097512, 0.00830567]}
      />
      <group
        position={[-0.23900369, 3.41537857, 0.45911944]}
        scale={[0.11061922, 0.05818476, 0.0070218]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_1.geometry}
          material={nodes.Cube067_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_2.geometry}
          material={nodes.Cube067_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube271.geometry}
        material={nodes.Cube271.material}
        position={[1.43994653, 2.56281567, 0]}
        scale={[0.00474772, 0.00901382, 0.18309635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube272.geometry}
        material={nodes.Cube272.material}
        position={[-0.49639022, 3.07560682, 0.03452693]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.11419222, 0.08015293, 0.00860869]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube273.geometry}
        material={nodes.Cube273.material}
        position={[-0.52029502, 3.30459428, -0.03439415]}
        scale={[0.08011124, 0.14883454, 0.04527115]}
      />
    </group>
  )
}

useGLTF.preload('/wiz_master.glb')